apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- servertransport.yaml
- authentik-environment-external.yaml
- authentik-postgres.yaml
- authentik-release.yaml
