---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authentik
  namespace: flux-system
spec:
  interval: 10m0s
  timeout: 5m
  path: ./authentik
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: flux-system-additions-external-secrets
  postBuild:
    substitute:
      var_substitution_enabled: "true"
    substituteFrom:
      - kind: Secret
        name: clusterconfig
        optional: true
