apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- crds.yaml
- external-secrets.yaml
- cert-manager.yaml
- csi-driver-nfs.yaml
- flux-webhook.yaml
- reloader.yaml
- rke-patches.yaml
- cilium-bgp.yaml
- rook-ceph.yaml
- test.yaml
- cloudnative-pg.yaml
- flux-system-additions.yaml
- monitoring.yaml
- traefik.yaml
- traefik-out-of-cluster.yaml
- external-dns.yaml
- authentik.yaml
- linkwarden.yaml
- searxng.yaml


# - metallb.yaml
# - kube-auth-proxy.yaml
# - trivy-operator.yaml
# - immich.yaml
# - linkding.yaml
# - vcluster.yaml
# - jenkins.yaml